/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "clevelander-pink": "#E91E63",
                "clevelander-dark": "#1a1a1a",
                'clevelander-navy': '#1e3a5f',
                "error-container": "#ffdad6",
                "secondary-container": "#92f3ec",
                error: "#ba1a1a",
                "on-secondary-fixed-variant": "#00504c",
                "primary-fixed-dim": "#ffb3b5",
                "on-tertiary-container": "#f8fcff",
                "tertiary-fixed": "#c1e8fb",
                secondary: "#006a65",
                "inverse-surface": "#303030",
                "on-secondary-container": "#00716c",
                surface: "#fbf9f8",
                "on-surface": "#1b1c1c",
                "tertiary-fixed-dim": "#a5ccde",
                "tertiary-container": "#537989",
                "on-tertiary-fixed": "#001f29",
                "on-background": "#1b1c1c",
                "inverse-on-surface": "#f2f0f0",
                "primary-fixed": "#ffdada",
                outline: "#916e6f",
                "surface-container-low": "#f5f3f3",
                "surface-container-lowest": "#ffffff",
                background: "#fbf9f8",
                "surface-tint": "#be0035",
                "surface-container-highest": "#e3e2e2",
                "on-secondary": "#ffffff",
                "surface-container": "#efeded",
                "surface-container-high": "#e9e8e7",
                "on-tertiary": "#ffffff",
                "on-secondary-fixed": "#00201e",
                primary: "#b90034",
                "secondary-fixed-dim": "#75d6d0",
                "inverse-primary": "#ffb3b5",
                "on-primary-fixed-variant": "#920027",
                "on-tertiary-fixed-variant": "#254c5b",
                "on-error-container": "#93000a",
                "primary-container": "#e41445",
                "outline-variant": "#e6bdbd",
                "on-error": "#ffffff",
                tertiary: "#3a6070",
                "surface-dim": "#dbdad9",
                "surface-bright": "#fbf9f8",
                "on-surface-variant": "#5d3f40",
                "surface-variant": "#e3e2e2",
                "on-primary": "#ffffff",
                "on-primary-fixed": "#40000c",
                "secondary-fixed": "#92f3ec",
                "on-primary-container": "#fffbfa",
                "error-dim": "#6b0221",
                "surface-container": "#eceef1",
                "secondary-dim": "#4f5263",
                "surface-bright": "#f9f9fb",
                "tertiary-dim": "#5a4f66",
                "primary-dim": "#5c4d6d",
            },
            fontFamily: {
                headline: ["Montserrat"],
                body: ["Plus Jakarta Sans"],
                label: ["Plus Jakarta Sans"],
                sans: ["Montserrat", "sans-serif"],
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem",
            },
        },
    },
    plugins: [
        require("@tailwindcss/forms"),
        require("@tailwindcss/aspect-ratio"),
        require("@tailwindcss/typography"),
        require("@tailwindcss/container-queries"),
    ],
};
